version: '2.4'

services:
  nginx:
    image: nginx
    volumes:
      - ./static:/app/static
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - "82:80"
    depends_on:
      - django
  db:
    image: postgres:13.3
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
  rabbit:
    image: "rabbitmq:3"
  redis:
    image: "redis:alpine"
  celery:
    build: .
    image: app
    command: celery -A standings worker -l info
    restart: always
    env_file:
      - '.env'
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    image: app
    command: celery -A standings beat -l info
    restart: always
    env_file:
      - '.env'
    depends_on:
      - db
      - redis
      - rabbit
  go:
    build: .
    image: app
    command: go run /app/cmd
    restart: always
    env_file:
      - '.env'
    depends_on:
      - db
      - rabbit
  django:
    build: .
    image: app
    restart: always
    env_file:
      - '.env'
    depends_on:
      - db
      - rabbit
      - celery
      - celery-beat
  init_db:
    build: .
    image: app
    command: bash -c "python3 manage.py migrate && python3 manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL"
    env_file:
      - '.env'
    depends_on:
      - db
  collectstatic:
    build: .
    image: app
    volumes:
      - ./static:/app/static
    command: python3 manage.py collectstatic --noinput