# Generated by Django 4.1.3 on 2022-11-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('pcms_id', models.CharField(max_length=1000)),
                ('contest_id', models.CharField(max_length=1000)),
                ('scoring_model', models.CharField(choices=[('ioi', 'ioi'), ('icpc', 'icpc')], max_length=10)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('login', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('api_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcms_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('pcms_id', models.CharField(max_length=1000)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.problem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.group'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problem',
            field=models.ManyToManyField(through='checker.ContestProblem', to='checker.problem'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcms_id', models.CharField(max_length=1000)),
                ('score', models.IntegerField()),
                ('outcome', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('time', models.IntegerField()),
                ('language', models.CharField(max_length=1000)),
                ('participant', models.ForeignKey(on_delete=models.Model, to='checker.participant')),
                ('problem_contest', models.ForeignKey(on_delete=models.Model, to='checker.contestproblem')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_checking_result', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('checking_start_time', models.DateTimeField(blank=True, null=True)),
                ('checking_end_time', models.DateTimeField(blank=True, null=True)),
                ('attempt_lhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_lhs', to='checker.attempt')),
                ('attempt_rhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_rhs', to='checker.attempt')),
            ],
            options={
                'unique_together': {('attempt_lhs', 'attempt_rhs')},
            },
        ),
    ]
