# Generated by Django 4.1.3 on 2022-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_page_downloaded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
