# Generated by Django 4.1.3 on 2022-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_contest_last_page_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='outcome',
            field=models.CharField(choices=[('undefined', 'undefined'), ('fl', 'fail'), ('unknown', 'unknown'), ('accepted', 'accepted'), ('partially-correct', 'partially-correct'), ('relative-scoring', 'relative-scoring'), ('compilation-error', 'compilation-error'), ('wrong-answer', 'wrong-answer'), ('presentation-error', 'presentation-error'), ('runtime-error', 'runtime-error'), ('time-limit-exceeded', 'time-limit-exceeded'), ('memory-limit-exceeded', 'memory-limit-exceeded'), ('output-limit-exceeded', 'output-limit-exceeded'), ('idleness-limit-exceeded', 'idleness-limit-exceeded'), ('security-violation', 'security-violation'), ('cancelled', 'cancelled')], max_length=1000),
        ),
    ]
