# Generated by Django 4.1.3 on 2022-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_alter_attempt_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/sources/')),
            ],
        ),
    ]
