# Generated by Django 4.1.3 on 2022-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_fileuploadtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_attempt_id_downloaded',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='scoring_model',
            field=models.CharField(choices=[('ioi', 'ioi'), ('icpc', 'icpc')], max_length=50),
        ),
    ]
