# Generated by Django 4.1.3 on 2022-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_participant_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='contest',
        ),
        migrations.AddField(
            model_name='participant',
            name='contest',
            field=models.ManyToManyField(blank=True, null=True, to='checker.contest'),
        ),
    ]
