# Generated by Django 4.1.3 on 2022-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_remove_participant_contest_participant_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
