# Generated by Django 4.1.3 on 2022-11-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0008_alter_attempt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('p', 'pcms auth'), ('b', 'builtin auth')], max_length=2)),
                ('login_pcms', models.CharField(blank=True, max_length=100, null=True)),
                ('password_pcms', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usertype',
            constraint=models.CheckConstraint(check=models.Q(('auth_type', 'p'), models.Q(('auth_type', 'b'), ('login_pcms__isnull', False), ('password_pcms__isnull', False)), _connector='OR'), name='checker_usertype_name_should have or login_pcms and password or auth_type pcms'),
        ),
    ]
