# Generated by Django 4.1.3 on 2022-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_usertype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usertype',
            name='checker_usertype_name_should have or login_pcms and password or auth_type pcms',
        ),
        migrations.AddConstraint(
            model_name='usertype',
            constraint=models.CheckConstraint(check=models.Q(('auth_type', 'p'), models.Q(('auth_type', 'b'), ('login_pcms__isnull', False), ('password_pcms__isnull', False)), _connector='OR'), name='checker_usertype If you choose builtin auth, you should enter pcms login and password'),
        ),
    ]
