# Generated by Django 4.1.3 on 2022-11-10 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_contestproblem_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_attempt_parsing_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='last_contest_problems_parsing_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
