# Generated by Django 4.1.3 on 2022-11-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_contest_last_attempt_parsing_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('login', 'password', 'api_url')},
        ),
    ]
