# Generated by Django 4.1.3 on 2022-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_alter_group_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='group',
        ),
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='checker.group'),
        ),
    ]
