# Generated by Django 4.1.3 on 2022-11-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0017_alter_attemptscheckjobs_script_checking_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptscheckjobs',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.job'),
        ),
    ]
