# Generated by Django 4.1.3 on 2022-11-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0019_attempt_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
