# Generated by Django 4.1.3 on 2022-11-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0020_delete_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploadTest',
        ),
    ]
