# Generated by Django 4.1.3 on 2022-11-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0021_delete_fileuploadtest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['alias', 'time', 'pcms_id']},
        ),
    ]
