# Generated by Django 4.1.3 on 2022-11-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0022_alter_attempt_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('pcms_id',)},
        ),
    ]
