# Generated by Django 4.1.3 on 2022-11-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0023_alter_attempt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.participant'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='problem_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.contestproblem'),
        ),
    ]
