# Generated by Django 4.1.3 on 2022-11-12 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checker', '0025_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(blank=True, to='checker.group'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contest',
            field=models.ManyToManyField(blank=True, to='checker.contest'),
        ),
        migrations.AlterField(
            model_name='job',
            name='groups',
            field=models.ManyToManyField(blank=True, to='checker.group'),
        ),
        migrations.AlterField(
            model_name='job',
            name='participant',
            field=models.ManyToManyField(blank=True, to='checker.participant'),
        ),
        migrations.AlterField(
            model_name='job',
            name='problems',
            field=models.ManyToManyField(blank=True, to='checker.problem'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contest',
            field=models.ManyToManyField(blank=True, to='checker.contest'),
        ),
    ]
