# Generated by Django 4.1.3 on 2022-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0026_alter_contest_group_alter_job_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptscheckjobs',
            name='manual_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
