# Generated by Django 4.1.3 on 2022-11-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0027_attemptscheckjobs_manual_check_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptscheckjobs',
            options={'ordering': ['pk']},
        ),
    ]
