# Generated by Django 4.1.3 on 2023-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0028_alter_attemptscheckjobs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
